#!/usr/bin/env node
/**
 * Generates src/app/palette.css — the light/dark remap of Tailwind's colour scales.
 *
 *   node scripts/gen-palette.mjs
 *
 * Components keep their Tailwind class names (bg-slate-50, text-sky-600, …); this file redefines
 * the --color-<family>-<shade> variables those utilities read, once per theme.
 *
 * Light theme: each accent family is interpolated from three anchors (500 vivid, 600 primary, 700 deep).
 * Dark theme: the ramp is inverted — 50–400 become dark tints over the tile colour, 600 is the bright
 * accent (readable as text; solid buttons put tile-coloured "white" text on it), 700–950 get lighter.
 * sky / blue / indigo deliberately share one accent so the app has a single primary colour.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
const WHITE = "#ffffff";
const BLACK = "#000000";
const TILE_DARK = "#141519";

// family -> [light 500, light 600, light 700, dark accent]
const ACCENTS = {
  blue: ["#4a7bf0", "#2c5bd0", "#2148ad", "#6b97ff"],
  violet: ["#8a63e0", "#6a3fc8", "#55309f", "#b9a3ff"],
  teal: ["#14a38d", "#0b7666", "#08594d", "#3cc8b4"],
  cyan: ["#1aa3c4", "#0b7891", "#095e72", "#4cc3dc"],
  amber: ["#e0a222", "#9a6200", "#7a4e00", "#f2b84b"],
  orange: ["#f07b3a", "#c2560f", "#9a420a", "#ff9b5e"],
  coral: ["#e5584a", "#c2372a", "#9c2a20", "#ff7d6e"],
};
const FAMILY_OF = {
  sky: "blue", blue: "blue", indigo: "blue",
  violet: "violet", purple: "violet",
  emerald: "teal", green: "teal", teal: "teal", lime: "teal",
  cyan: "cyan",
  amber: "amber", yellow: "amber",
  orange: "orange",
  rose: "coral", red: "coral", pink: "coral", fuchsia: "coral",
};
const NEUTRALS = ["slate", "gray", "zinc", "neutral", "stone"];
const NEUTRAL_LIGHT = ["#f5f6f8", "#eceef2", "#dfe2e8", "#c9cdd5", "#80858f", "#646973", "#4d525b", "#383c44", "#24272d", "#14161b", "#0c0d10"];
const NEUTRAL_DARK = ["#0c0d10", "#1a1b20", "#26282e", "#34363d", "#7c808a", "#8d9098", "#a3a6ad", "#c4c7cd", "#dcdee2", "#f1f2f4", "#fafafb"];

const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
/** sRGB mix: `t` is the share of `a`. */
const mix = (a, b, t) => {
  const [x, y] = [rgb(a), rgb(b)];
  return "#" + x.map((v, i) => Math.round(v * t + y[i] * (1 - t)).toString(16).padStart(2, "0")).join("");
};

function lightRamp([v, p, d]) {
  return [mix(v, WHITE, 0.07), mix(v, WHITE, 0.14), mix(v, WHITE, 0.28), mix(v, WHITE, 0.48), mix(v, WHITE, 0.74),
    v, p, d, mix(d, BLACK, 0.8), mix(d, BLACK, 0.66), mix(d, BLACK, 0.5)];
}
function darkRamp(a) {
  return [mix(a, TILE_DARK, 0.1), mix(a, TILE_DARK, 0.16), mix(a, TILE_DARK, 0.28), mix(a, TILE_DARK, 0.45), mix(a, TILE_DARK, 0.7),
    mix(a, TILE_DARK, 0.88), a, mix(a, WHITE, 0.8), mix(a, WHITE, 0.62), mix(a, WHITE, 0.46), mix(a, WHITE, 0.36)];
}

function block(theme) {
  const lines = [`  --color-white: ${theme === "light" ? WHITE : TILE_DARK};`];
  const neutral = theme === "light" ? NEUTRAL_LIGHT : NEUTRAL_DARK;
  for (const n of NEUTRALS) SHADES.forEach((s, i) => lines.push(`  --color-${n}-${s}: ${neutral[i]};`));
  for (const [tw, fam] of Object.entries(FAMILY_OF)) {
    const ramp = theme === "light" ? lightRamp(ACCENTS[fam]) : darkRamp(ACCENTS[fam][3]);
    SHADES.forEach((s, i) => lines.push(`  --color-${tw}-${s}: ${ramp[i]};`));
  }
  return lines.join("\n");
}

const light = block("light");
const css = `/* GENERATED by scripts/gen-palette.mjs — edit the anchors there and re-run; do not edit by hand. */

:root {
${light}
}

:root[data-theme="dark"] {
${block("dark")}
}

/* Code, terminal and graph surfaces are authored dark (bg-slate-900 + light syntax colours from
   lib/highlight.ts). Inside them the dark theme restores the light-theme ramp so they stay dark. */
:root[data-theme="dark"] .code-surface {
${light}
}
`;

const out = fileURLToPath(new URL("../src/app/palette.css", import.meta.url));
writeFileSync(out, css);
console.log(`wrote ${out}`);
